Outputs:
  app-1-logs:
    type: log-file
    name: app1.log
    flush_interval: 5
  app-2-logs:
    type: log-file
    name: app2.log
    flush_interval: 5

Processes:
    app-json-logs:
      type: json
      pre-mutations:
        - name: mask-ip
          value: |+
            ->(event) {
              event[:ip] = '*.*.*.*'
              return event
            }
      post-mutations:
        - name: convert-to-string
          value: |+
            ->(event) {
              return event.to_str
            }

Inputs:
  app1_logs:
    type: http-json
    process: app-json-logs
    output: app-1-logs
    host: '0.0.0.0'
    port: 8080
  app2_logs:
    type: http-json
    process: app-json-logs
    output: app-2-logs
    host: '0.0.0.0'
    port: 8081